import { chromium } from 'playwright-core'
import { mkdir } from 'node:fs/promises'

const baseUrl = process.env.APP_URL || 'http://127.0.0.1:5173'
const browser = await chromium.launch({
  executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  headless: true,
})

await mkdir('artifacts', { recursive: true })
const issues = []

async function inspectViewport(page, name) {
  const layout = await page.evaluate(() => ({
    viewport: window.innerWidth,
    documentWidth: document.documentElement.scrollWidth,
    bodyWidth: document.body.scrollWidth,
  }))
  if (layout.documentWidth > layout.viewport || layout.bodyWidth > layout.viewport) {
    issues.push(`${name}: horizontal overflow ${JSON.stringify(layout)}`)
  }
}

const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 })
desktop.on('console', (message) => message.type() === 'error' && issues.push(`console: ${message.text()}`))
desktop.on('pageerror', (error) => issues.push(`page: ${error.message}`))
await desktop.goto(baseUrl, { waitUntil: 'networkidle' })
await inspectViewport(desktop, 'dashboard-desktop')
await desktop.screenshot({ path: 'artifacts/dashboard-desktop.png', fullPage: true })

const desktopNotifications = desktop.getByRole('button', { name: 'Notificaciones', exact: true })
if ((await desktopNotifications.locator('.notification-count').innerText()).trim() !== '3') issues.push('unexpected initial notification count')
await desktopNotifications.click()
const notificationPanel = desktop.locator('.notification-panel')
await notificationPanel.getByText('Stock crítico', { exact: true }).waitFor()
await notificationPanel.getByText('Despachos pendientes', { exact: true }).waitFor()
await notificationPanel.getByText('Resumen de ventas', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/notifications-desktop.png', fullPage: true })
await notificationPanel.getByRole('button', { name: 'Marcar todas', exact: true }).click()
if (await desktopNotifications.locator('.notification-count').count()) issues.push('notification badge remained after marking all as read')
await notificationPanel.getByRole('button', { name: 'Configurar notificaciones', exact: true }).click()
await desktop.locator('.settings-heading').getByRole('heading', { name: 'Notificaciones', exact: true }).waitFor()
await desktop.getByLabel('Días de anticipación').fill('20')
await desktop.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
await desktop.getByText('Configuración guardada correctamente', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/notification-settings-desktop.png', fullPage: true })

await desktop.getByRole('button', { name: 'Configuración', exact: true }).click()
await desktop.getByRole('button', { name: /Usuarios y permisos/ }).click()
await desktop.getByText('Camila Soto', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/users-desktop.png', fullPage: true })
await desktop.getByRole('button', { name: 'Nuevo usuario', exact: true }).click()
const userDialog = desktop.getByRole('dialog')
await userDialog.getByLabel('Nombre completo').fill('Daniela Ruiz')
await userDialog.getByLabel('Correo electrónico').fill('daniela@ferreterialosnogales.cl')
await userDialog.getByLabel('Rol').selectOption('Vendedor')
await userDialog.getByRole('button', { name: 'Guardar usuario', exact: true }).click()
await desktop.getByText('Usuario creado correctamente', { exact: true }).waitFor()
await desktop.getByText('Daniela Ruiz', { exact: true }).waitFor()
await desktop.getByRole('button', { name: /Ventas y caja/ }).click()
await desktop.getByLabel('Nombre de caja').fill('Caja Principal')
await desktop.getByLabel('Medio de pago predeterminado').selectOption('Efectivo')
await desktop.getByLabel('Crédito', { exact: true }).uncheck()
await desktop.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
await desktop.getByText('Configuración guardada correctamente', { exact: true }).waitFor()
await desktop.getByRole('button', { name: 'Punto de venta' }).click()
if ((await desktop.locator('.cart-heading .eyebrow').innerText()).trim().toLowerCase() !== 'caja principal') issues.push('configured register was not applied to POS')
if (await desktop.locator('.payment-tabs').getByRole('button', { name: 'Crédito', exact: true }).count()) issues.push('disabled payment method is still visible in POS')
if (!(await desktop.locator('.payment-tabs').getByRole('button', { name: 'Efectivo', exact: true }).getAttribute('class'))?.includes('active')) issues.push('default payment was not applied to POS')
await desktop.getByRole('button', { name: /Ventas en espera/ }).click()
const initialHeldDialog = desktop.getByRole('dialog')
await initialHeldDialog.getByText('ESP-001', { exact: true }).first().waitFor()
await initialHeldDialog.getByRole('button', { name: /ESP-002/ }).click()
await desktop.screenshot({ path: 'artifacts/held-sales-desktop.png', fullPage: true })
await initialHeldDialog.getByRole('button', { name: 'Eliminar', exact: true }).click()
await initialHeldDialog.getByRole('button', { name: 'Confirmar eliminación', exact: true }).click()
if (await initialHeldDialog.getByText('ESP-002', { exact: true }).count()) issues.push('deleted held sale is still visible')
await initialHeldDialog.getByRole('button', { name: 'Cerrar', exact: true }).click()
await desktop.getByRole('button', { name: /Taladro percutor/ }).click()
await desktop.getByRole('button', { name: /Disco corte metal/ }).click()
await desktop.getByRole('button', { name: /Disco corte metal/ }).click()
await inspectViewport(desktop, 'pos-desktop')
await desktop.screenshot({ path: 'artifacts/pos-desktop.png', fullPage: true })
const checkoutText = await desktop.locator('.checkout-button').innerText()
if (!checkoutText.includes('$74.970')) issues.push(`unexpected checkout total: ${checkoutText}`)
await desktop.getByRole('button', { name: 'Dejar en espera', exact: true }).click()
if (!(await desktop.locator('.checkout-button').innerText()).includes('$0')) issues.push('holding a sale did not clear the cart')
await desktop.getByRole('button', { name: /Ventas en espera/ }).click()
const resumedHeldDialog = desktop.getByRole('dialog')
await resumedHeldDialog.getByText('ESP-003', { exact: true }).first().waitFor()
await resumedHeldDialog.getByRole('button', { name: 'Retomar venta', exact: true }).click()
if (!(await desktop.locator('.checkout-button').innerText()).includes('$74.970')) issues.push('resumed sale did not restore the cart')
await desktop.getByRole('button', { name: 'Cotizar', exact: true }).click()
const firstQuote = desktop.getByRole('dialog')
await firstQuote.getByRole('heading', { name: 'Cotización comercial' }).waitFor()
await firstQuote.getByText('COT-000001', { exact: true }).first().waitFor()
await firstQuote.getByText('Taladro percutor 13 mm', { exact: true }).waitFor()
await firstQuote.getByText('$74.970', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/quote-desktop.png', fullPage: true })
await firstQuote.getByRole('button', { name: 'Cerrar', exact: true }).click()
await desktop.getByRole('button', { name: 'Cotizar', exact: true }).click()
const secondQuote = desktop.getByRole('dialog')
await secondQuote.getByText('COT-000002', { exact: true }).first().waitFor()
await secondQuote.getByRole('button', { name: 'Cerrar', exact: true }).click()
if (!(await desktop.locator('.checkout-button').innerText()).includes('$74.970')) issues.push('quote changed the active cart')
await desktopNotifications.click()
await desktop.locator('.notification-panel').getByText('Cotizaciones por vencer', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/quote-notification-desktop.png', fullPage: true })
await desktopNotifications.click()
await desktop.locator('.payment-tabs').getByRole('button', { name: 'Efectivo', exact: true }).click()
await desktop.locator('.checkout-button').click()
const receiptDialog = desktop.getByRole('dialog')
await receiptDialog.getByRole('heading', { name: 'Venta completada' }).waitFor()
await receiptDialog.getByText('Ferretería Los Nogales', { exact: true }).waitFor()
await receiptDialog.getByText('Taladro percutor 13 mm', { exact: true }).waitFor()
await receiptDialog.getByText('Efectivo', { exact: true }).waitFor()
await receiptDialog.getByText('$74.970', { exact: true }).waitFor()
await desktop.screenshot({ path: 'artifacts/receipt-desktop.png', fullPage: true })
await receiptDialog.getByRole('button', { name: 'Finalizar' }).click()

await desktop.getByRole('button', { name: 'Inventario' }).click()
await desktop.getByRole('button', { name: 'Nuevo producto' }).click()
await desktop.getByRole('dialog').waitFor()
await desktop.keyboard.press('Escape')
await desktop.getByRole('button', { name: 'Ingresos' }).click()
await desktop.getByRole('button', { name: 'Nuevo ingreso' }).click()
await desktop.getByRole('dialog').waitFor()
await desktop.keyboard.press('Escape')
await desktop.getByRole('button', { name: 'Despachos' }).click()
await desktop.getByRole('button', { name: 'Nuevo despacho' }).click()
await desktop.getByRole('dialog').waitFor()
await desktop.keyboard.press('Escape')
await desktop.getByRole('button', { name: 'Proveedores' }).click()
await desktop.locator('.toast').waitFor({ state: 'hidden' })
await inspectViewport(desktop, 'suppliers-desktop')
await desktop.screenshot({ path: 'artifacts/suppliers-desktop.png', fullPage: true })
await desktop.getByRole('button', { name: 'Nuevo proveedor' }).click()
const supplierDialog = desktop.getByRole('dialog')
await supplierDialog.getByLabel('Razón social').fill('Test Industrial SpA')
await supplierDialog.getByLabel('RUT').fill('76.555.444-3')
await supplierDialog.getByLabel('Rubro principal').fill('Insumos industriales')
await supplierDialog.getByLabel('Nombre').fill('Camila Reyes')
await supplierDialog.getByLabel('Cargo').fill('Ejecutiva comercial')
await supplierDialog.getByLabel('Teléfono').fill('+56 9 5555 4444')
await supplierDialog.getByLabel('Correo').fill('camila@testindustrial.cl')
await supplierDialog.getByLabel('Dirección').fill('Av. Industrial 123, Santiago')
await supplierDialog.getByLabel('Condición de pago').fill('30 días')
await supplierDialog.getByLabel('Tiempo de entrega').fill('2 días')
await supplierDialog.getByRole('button', { name: 'Guardar proveedor' }).click()
await desktop.getByText('Proveedor agregado a la agenda').waitFor()
await desktop.getByText('Test Industrial SpA', { exact: true }).first().waitFor()
await desktop.getByRole('button', { name: 'Ingresos' }).click()
await desktop.getByRole('button', { name: 'Nuevo ingreso' }).click()
const supplierOptions = await desktop.getByRole('dialog').getByLabel('Proveedor').locator('option').allTextContents()
if (!supplierOptions.includes('Test Industrial SpA')) issues.push('new supplier missing from receipt form')
await desktop.keyboard.press('Escape')
await desktop.getByRole('button', { name: 'Reportes' }).click()
const firstSaleRow = desktop.locator('.sales-report-table tbody tr').first()
const firstSaleCells = firstSaleRow.locator('td')
const firstSaleFolio = (await firstSaleCells.nth(0).innerText()).trim()
const firstSaleSeller = (await firstSaleCells.nth(4).innerText()).trim()
const firstSalePayment = (await firstSaleCells.nth(5).innerText()).trim()
if (firstSaleFolio !== 'V-2850') issues.push(`latest sale is not first: ${firstSaleFolio}`)
if (firstSaleSeller !== 'Matías Dintrans') issues.push(`sale responsible was not preserved: ${firstSaleSeller}`)
if (firstSalePayment !== 'Efectivo') issues.push(`sale payment was not preserved: ${firstSalePayment}`)
if (await desktop.getByText('No informado', { exact: true }).count()) issues.push('reports still contain an unknown payment method')
await inspectViewport(desktop, 'reports-desktop')
await desktop.screenshot({ path: 'artifacts/reports-desktop.png', fullPage: true })
await desktop.locator('.period-switch').getByRole('button', { name: 'Día', exact: true }).click()
await desktop.getByLabel('Fecha').fill('2026-09-21')
await desktop.locator('.report-search input').fill('Constructora')
const filteredRows = await desktop.locator('.sales-report-table tbody tr').count()
if (filteredRows !== 1) issues.push(`expected 1 filtered sale, found ${filteredRows}`)
await desktop.locator('.report-search input').fill('')
const downloadPromise = desktop.waitForEvent('download')
await desktop.getByRole('button', { name: 'Exportar Excel' }).click()
const download = await downloadPromise
if (!download.suggestedFilename().endsWith('.xlsx')) issues.push(`unexpected export filename: ${download.suggestedFilename()}`)
await download.saveAs('artifacts/ventas-reporte.xlsx')
await desktop.getByRole('button', { name: 'Configuración', exact: true }).click()
await desktop.getByRole('button', { name: /Respaldo/ }).click()
await inspectViewport(desktop, 'settings-desktop')
await desktop.screenshot({ path: 'artifacts/settings-desktop.png', fullPage: true })
const backupPromise = desktop.waitForEvent('download')
await desktop.getByRole('button', { name: /Descargar respaldo/ }).click()
const backup = await backupPromise
if (!backup.suggestedFilename().endsWith('.json')) issues.push(`unexpected backup filename: ${backup.suggestedFilename()}`)
await backup.saveAs('artifacts/respaldo-erp.json')
await desktop.getByRole('button', { name: 'Cambiar usuario', exact: true }).click()
await desktop.locator('.user-menu').getByRole('button', { name: /Camila Soto/ }).click()
await desktop.waitForTimeout(500)
if (!(await desktopNotifications.locator('.notification-count').count())) issues.push('notification read state was not isolated by user')
if (await desktop.locator('.sidebar').getByRole('button', { name: 'Configuración', exact: true }).count()) issues.push('seller can access settings navigation')
if (await desktop.locator('.sidebar').getByRole('button', { name: 'Ingresos', exact: true }).count()) issues.push('seller can access receipts navigation')
const sellerNavigation = await desktop.locator('.sidebar .main-nav button').allInnerTexts()
const sellerInventory = desktop.locator('.sidebar .main-nav button').filter({ hasText: 'Inventario' })
if (!(await sellerInventory.count())) issues.push(`seller is missing inventory access: ${JSON.stringify(sellerNavigation)}`)
else {
  await sellerInventory.click()
  if (await desktop.getByRole('button', { name: 'Nuevo producto', exact: true }).count()) issues.push('seller can create inventory products')
}
await desktop.screenshot({ path: 'artifacts/seller-permissions-desktop.png', fullPage: true })
await desktop.getByRole('button', { name: 'Cambiar usuario', exact: true }).click()
await desktop.locator('.user-menu').getByRole('button', { name: /Matías Dintrans/ }).click()

const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 })
mobile.on('console', (message) => message.type() === 'error' && issues.push(`mobile console: ${message.text()}`))
mobile.on('pageerror', (error) => issues.push(`mobile page: ${error.message}`))
await mobile.goto(baseUrl, { waitUntil: 'networkidle' })
await inspectViewport(mobile, 'dashboard-mobile')
await mobile.screenshot({ path: 'artifacts/dashboard-mobile.png', fullPage: true })
await mobile.getByRole('button', { name: 'Notificaciones', exact: true }).click()
await mobile.locator('.notification-panel').getByText('Stock crítico', { exact: true }).waitFor()
await inspectViewport(mobile, 'notifications-mobile')
await mobile.screenshot({ path: 'artifacts/notifications-mobile.png' })
await mobile.getByRole('button', { name: 'Notificaciones', exact: true }).click()
await mobile.locator('.mobile-nav').getByRole('button', { name: 'Venta', exact: true }).click()
await inspectViewport(mobile, 'pos-mobile')
await mobile.screenshot({ path: 'artifacts/pos-mobile.png', fullPage: true })
await mobile.getByRole('button', { name: /Ventas en espera/ }).click()
const mobileHeld = mobile.getByRole('dialog')
await mobileHeld.getByText('ESP-001', { exact: true }).first().waitFor()
await inspectViewport(mobile, 'held-sales-mobile')
await mobile.screenshot({ path: 'artifacts/held-sales-mobile.png' })
await mobileHeld.getByRole('button', { name: 'Cerrar', exact: true }).click()
await mobile.getByRole('button', { name: /Taladro percutor/ }).click()
await mobile.locator('.checkout-button').scrollIntoViewIfNeeded()
await mobile.getByRole('button', { name: 'Cotizar', exact: true }).click()
const mobileQuote = mobile.getByRole('dialog')
await mobileQuote.getByRole('heading', { name: 'Cotización comercial' }).waitFor()
await inspectViewport(mobile, 'quote-mobile')
await mobile.screenshot({ path: 'artifacts/quote-mobile.png' })
await mobileQuote.getByRole('button', { name: 'Cerrar', exact: true }).click()
await mobile.locator('.checkout-button').click()
const mobileReceipt = mobile.getByRole('dialog')
await mobileReceipt.getByRole('heading', { name: 'Venta completada' }).waitFor()
await inspectViewport(mobile, 'receipt-mobile')
await mobile.screenshot({ path: 'artifacts/receipt-mobile.png' })
await mobileReceipt.getByRole('button', { name: 'Finalizar' }).click()
await mobile.locator('.mobile-menu').click()
await mobile.locator('.sidebar').getByRole('button', { name: 'Proveedores', exact: true }).click()
await mobile.waitForTimeout(350)
await inspectViewport(mobile, 'suppliers-mobile')
await mobile.screenshot({ path: 'artifacts/suppliers-mobile.png', fullPage: true })
await mobile.locator('.mobile-menu').click()
await mobile.locator('.sidebar').getByRole('button', { name: 'Reportes', exact: true }).click()
await mobile.waitForTimeout(350)
await inspectViewport(mobile, 'reports-mobile')
await mobile.screenshot({ path: 'artifacts/reports-mobile.png', fullPage: true })
await mobile.locator('.mobile-menu').click()
await mobile.locator('.sidebar').getByRole('button', { name: 'Configuración', exact: true }).click()
await mobile.waitForTimeout(350)
await inspectViewport(mobile, 'settings-mobile')
await mobile.screenshot({ path: 'artifacts/settings-mobile.png', fullPage: true })
await mobile.getByRole('button', { name: /Usuarios y permisos/ }).click()
await mobile.getByText('Camila Soto', { exact: true }).waitFor()
await inspectViewport(mobile, 'users-mobile')
await mobile.screenshot({ path: 'artifacts/users-mobile.png', fullPage: true })

console.log(JSON.stringify({ ok: issues.length === 0, issues }, null, 2))
await browser.close()
